"""MIND descriptors for modality-invariant IR--visible structure matching.

All tensors in this module use the PyTorch image layout ``[B, C, H, W]``.
``MINDDescriptor`` accepts a single-channel image and returns an eight-channel
descriptor on the *same pixel grid* ``[B, 8, H, W]``. It uses only tensor
operations, therefore works with batches, CUDA, autograd and mixed precision.

For every neighbour offset r, the descriptor first computes the patch
self-similarity distance

    SSD_r(p) = mean_{u in patch} (I(p + u) - I(p + r + u))^2.

The eight distances are divided by their per-pixel mean and mapped with
``exp(-SSD / variance)``. An L2 normalisation across descriptor channels makes
the representation insensitive to local contrast scale. This is the MIND
principle: compare local self-similarity rather than raw IR/VIS intensities.
"""

from __future__ import annotations

from typing import Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


def rgb_to_gray(image: torch.Tensor) -> torch.Tensor:
    """Convert ``[B, 3, H, W]`` RGB in any numeric range to luminance.

    The operation is deliberately not clamped: MIND is based on relative local
    distances and callers may pass normalised tensors outside ``[0, 1]``.
    """
    if image.ndim != 4:
        raise ValueError(f"expected [B,C,H,W], got {tuple(image.shape)}")
    if image.shape[1] == 1:
        return image
    if image.shape[1] != 3:
        raise ValueError(
            "rgb_to_gray accepts one-channel IR or three-channel RGB, got "
            f"C={image.shape[1]}")
    return (0.299 * image[:, 0:1] + 0.587 * image[:, 1:2]
            + 0.114 * image[:, 2:3])


class MINDDescriptor(nn.Module):
    """Patch self-similarity descriptor for a one-channel image.

    Args:
        patch_size: Odd square patch width used in each SSD calculation.
        radius: Neighbourhood radius. ``radius=1`` produces the standard eight
            offsets around a pixel and therefore eight descriptor channels.
        eps: Numerical lower bound for local variance and L2 normalisation.

    Input:
        image: ``[B, 1, H, W]`` float tensor.
    Output:
        Descriptor tensor ``[B, 8, H, W]`` for the default radius.
    """

    def __init__(self, patch_size: int = 3, radius: int = 1,
                 eps: float = 1e-6) -> None:
        super().__init__()
        if patch_size < 1 or patch_size % 2 == 0:
            raise ValueError("patch_size must be a positive odd integer")
        if radius < 1:
            raise ValueError("radius must be at least one")
        if eps <= 0:
            raise ValueError("eps must be positive")
        offsets = [(dy, dx) for dy in range(-radius, radius + 1)
                   for dx in range(-radius, radius + 1)
                   if (dy, dx) != (0, 0)]
        self.patch_size = int(patch_size)
        self.radius = int(radius)
        self.eps = float(eps)
        # A buffer follows the module to CUDA without becoming a parameter.
        self.register_buffer("offsets", torch.tensor(offsets, dtype=torch.long),
                             persistent=False)

    @property
    def channels(self) -> int:
        """Number of descriptor channels generated by the neighbourhood."""
        return int(self.offsets.shape[0])

    def _shift_replicate(self, image: torch.Tensor, dy: int,
                         dx: int) -> torch.Tensor:
        """Return ``image(p + [dy, dx])`` with replicate boundary handling."""
        _, _, height, width = image.shape
        pad = self.radius
        padded = F.pad(image, (pad, pad, pad, pad), mode="replicate")
        return padded[..., pad + dy:pad + dy + height, pad + dx:pad + dx + width]

    def forward(self, image: torch.Tensor) -> torch.Tensor:
        """Compute a normalised MIND descriptor without NumPy or CPU copies."""
        if image.ndim != 4 or image.shape[1] != 1:
            raise ValueError(
                "MINDDescriptor expects a one-channel [B,1,H,W] tensor, got "
                f"{tuple(image.shape)}")
        if image.shape[-2] < self.patch_size or image.shape[-1] < self.patch_size:
            raise ValueError(
                f"image spatial size {tuple(image.shape[-2:])} is smaller than "
                f"patch_size={self.patch_size}")
        if not image.is_floating_point():
            raise TypeError("MINDDescriptor requires a floating-point image")

        # Calculate one patch SSD map for each non-centre neighbour. Each map is
        # [B,1,H,W]; concatenation produces [B,K,H,W].
        distances = []
        patch_padding = self.patch_size // 2
        for dy, dx in self.offsets.tolist():
            shifted = self._shift_replicate(image, int(dy), int(dx))
            squared_difference = (image - shifted).square()
            distances.append(F.avg_pool2d(
                squared_difference,
                kernel_size=self.patch_size,
                stride=1,
                padding=patch_padding,
                count_include_pad=False))
        ssd = torch.cat(distances, dim=1)

        # Local normalisation is what suppresses modality-specific intensity
        # scale. Float32 accumulation protects this ratio under fp16 autocast.
        variance = ssd.float().mean(dim=1, keepdim=True).clamp_min(self.eps)
        descriptor = torch.exp(-ssd.float() / variance)
        descriptor = F.normalize(descriptor, p=2, dim=1, eps=self.eps)
        return descriptor.to(dtype=image.dtype)


def paired_mind(ir: torch.Tensor, vi: torch.Tensor,
                descriptor: MINDDescriptor) -> Tuple[torch.Tensor, torch.Tensor]:
    """Convenience wrapper used by the future registration network.

    Args:
        ir: Infrared image ``[B,1,H,W]``.
        vi: Visible RGB image ``[B,3,H,W]``.

    Returns:
        ``(D_ir, D_vi)`` with identical ``[B,K,H,W]`` shapes.
    """
    if ir.ndim != 4 or ir.shape[1] != 1:
        raise ValueError(f"IR must be [B,1,H,W], got {tuple(ir.shape)}")
    if vi.ndim != 4 or vi.shape[1] != 3:
        raise ValueError(f"VI must be [B,3,H,W], got {tuple(vi.shape)}")
    if ir.shape[0] != vi.shape[0] or ir.shape[-2:] != vi.shape[-2:]:
        raise ValueError("IR and VI must share batch size and spatial dimensions")
    return descriptor(ir), descriptor(rgb_to_gray(vi))
